package com.lab1;

public class Main {
    // Lab 1 Entry Point
    public static void main(String[] args) {
        var grammar = new Grammar();
        var fa = grammar.toFiniteAutomaton();

        System.out.println("1. Generating 5 valid strings");
        for (int i = 0; i < 5; i++) {
            var word = grammar.generateString();
            System.out.println("Generated: " + word);
        }

        System.out.println("\n2. Checking strings with automaton");
        // Let's test a word we know is valid (generated by grammar)
        var validWord = grammar.generateString();
        var isAccepted = fa.stringBelongToLanguage(validWord);
        System.out.println("Word '" + validWord + "' is accepted? " + isAccepted);

        // Let's test a fake word
        var fakeWord = "aaabbb"; 
        var isFakeAccepted = fa.stringBelongToLanguage(fakeWord);
        System.out.println("Word '" + fakeWord + "' is accepted? " + isFakeAccepted);
    }
}